<?xml version="1.0"?>
<package format="3">
  <name>course_bot_control</name>
  <version>0.0.1</version>
  <description>C++ motion control and A* path following for course_bot.</description>
  <maintainer email="1205058595@qq.com">jiangnan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
