<?xml version="1.0"?>
<package format="3">
  <name>course_bot_bringup</name>
  <version>0.0.1</version>
  <description>Top-level launch files for the course_bot project.</description>
  <maintainer email="1205058595@qq.com">jiangnan</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>course_bot_description</exec_depend>
  <exec_depend>course_bot_gazebo</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>launch_xml</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
