<?xml version="1.0"?>
<package format="3">
  <name>course_bot_slam</name>
  <version>0.1.0</version>
  <description>SLAM Toolbox mapping configuration for the course robot.</description>
  <maintainer email="1205058595@qq.com">jiangnan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>course_bot_description</exec_depend>
  <exec_depend>course_bot_bringup</exec_depend>
  <exec_depend>course_bot_gazebo</exec_depend>
  <exec_depend>course_bot_planner</exec_depend>
  <exec_depend>course_bot_control</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>teleop_twist_keyboard</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>launch_xml</exec_depend>

  <export><build_type>ament_cmake</build_type></export>
</package>
